import os
import glob
import pandas as pd
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

def process_attendance(base_dir, target_folder):
    input_dir = os.path.join(base_dir, target_folder)
    true_attendance_path = os.path.join(base_dir, "filtered_true_attendance.csv")
    
    if not os.path.exists(true_attendance_path):
        print(f"Error: Could not find True Attendance file at {true_attendance_path}")
        return

    # Load True Attendance
    true_df = pd.read_csv(true_attendance_path)
    true_df = true_df.set_index(true_df.columns[0]) 
    
    file_pattern = os.path.join(input_dir, "*_output.csv")
    output_files = glob.glob(file_pattern)
    
    if not output_files:
        print(f"No output CSV files found in {input_dir}")
        return

    dfs = []
    dates = []

    print("Processing files...")
    for file in output_files:
        filename = os.path.basename(file)
        date_str = filename.replace("_output.csv", "")
        dates.append(date_str)
        
        temp_df = pd.read_csv(file)
        temp_df = temp_df[['Name', 'Status', 'Detection Count']]
        temp_df = temp_df.rename(columns={'Status': 'Estimated', 'Detection Count': 'Count'})
        temp_df = temp_df.set_index('Name')
        
        if date_str in true_df.columns:
            temp_df['True'] = true_df[date_str]
        else:
            temp_df['True'] = "Unknown" 
            
        temp_df = temp_df[['Estimated', 'Count', 'True']]
        temp_df.columns = pd.MultiIndex.from_product([[date_str], temp_df.columns])
        dfs.append(temp_df)

    combined_df = pd.concat(dfs, axis=1)
    combined_df.index.name = 'Student Name'
    
    # Sort students alphabetically
    combined_df = combined_df.sort_index()
    
    # --- CALCULATE EFFICIENCY ---
    student_matches = pd.Series(0, index=combined_df.index)
    valid_sessions = len(dates)
    total_students = len(combined_df)
    
    date_efficiencies = {}
    
    for date in dates:
        est_col = combined_df[(date, 'Estimated')].astype(str).str.strip().str.lower()
        true_col = combined_df[(date, 'True')].astype(str).str.strip().str.lower()
        
        matches = (est_col == true_col)
        student_matches += matches.astype(int)
        
        date_accuracy = (matches.sum() / total_students) * 100
        date_efficiencies[(date, 'Estimated')] = f"{date_accuracy:.2f}%"
        date_efficiencies[(date, 'Count')] = ""
        date_efficiencies[(date, 'True')] = ""

    combined_df[('Overall', 'Efficiency')] = (student_matches / valid_sessions * 100).apply(lambda x: f"{x:.2f}%")
    
    total_matches_all = student_matches.sum()
    total_possible_data_points = total_students * valid_sessions
    overall_avg_efficiency = (total_matches_all / total_possible_data_points) * 100
    
    date_efficiencies[('Overall', 'Efficiency')] = f"{overall_avg_efficiency:.2f}%" 
    
    efficiency_row = pd.DataFrame([date_efficiencies], index=['EFFICIENCY'])
    combined_df = pd.concat([combined_df, efficiency_row])

    # --- SAVE FILES ---
    csv_output = os.path.join(input_dir, "Final_Report_With_Efficiency.csv")
    xlsx_output = os.path.join(input_dir, "Final_Report_With_Efficiency.xlsx")

    print("Saving files...")
    combined_df.to_csv(csv_output)
    combined_df.to_excel(xlsx_output)

    # --- EXCEL FORMATTING ---
    wb = openpyxl.load_workbook(xlsx_output)
    ws = wb.active
    ws.title = "Attendance Efficiency"

    # 1. Fix the Pandas layout quirks
    ws['A1'] = 'Student Names'
    ws.merge_cells('A1:A2')
    ws.delete_rows(3) # Removes the blank row generated by Pandas multi-index
    
    max_row = ws.max_row
    max_col = ws.max_column

    # 2. Style Definitions
    header_fill = PatternFill(start_color="2C3E50", end_color="2C3E50", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True)
    
    green_fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
    green_font = Font(color="006100")
    
    red_fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
    red_font = Font(color="9C0006")
    
    red_bold_font = Font(color="9C0006", bold=True)
    summary_fill = PatternFill(start_color="D5F5E3", end_color="D5F5E3", fill_type="solid")
    
    center_align = Alignment(horizontal="center", vertical="center")
    left_align = Alignment(horizontal="left", vertical="center")
    thin_border = Border(left=Side(style='thin', color='BDC3C7'), right=Side(style='thin', color='BDC3C7'), 
                         top=Side(style='thin', color='BDC3C7'), bottom=Side(style='thin', color='BDC3C7'))

    # Format Headers (Rows 1 and 2)
    for row in range(1, 3):
        for cell in ws[row]:
            try:
                cell.fill = header_fill
                cell.font = header_font
                cell.alignment = center_align
                cell.border = thin_border
            except AttributeError:
                pass
    ws['A1'].alignment = center_align # Ensure merged Student Name is centered

    # Format Data Rows
    for row_idx in range(3, max_row):
        for col_idx, cell in enumerate(ws[row_idx], start=1):
            try:
                cell.alignment = left_align if col_idx == 1 else center_align
                cell.border = thin_border
                
                if row_idx % 2 == 0:
                    cell.fill = PatternFill(start_color="F8F9F9", end_color="F8F9F9", fill_type="solid")
                    
                # Color Coding
                val = str(cell.value).strip().lower()
                if val == 'present':
                    cell.fill = green_fill
                    cell.font = green_font
                elif val == 'absent':
                    cell.fill = red_fill
                    cell.font = red_font
                elif val.endswith('%'):
                    num = float(val.strip('%'))
                    if num < 80.0:
                        cell.fill = red_fill
                        cell.font = red_font
            except (AttributeError, ValueError):
                pass

    # Format the bottom DATE EFFICIENCY row
    for col_idx, cell in enumerate(ws[max_row], start=1):
        try:
            cell.alignment = center_align
            cell.border = thin_border
            cell.fill = summary_fill
            cell.font = Font(bold=True)
            
            # Check for < 80% on summary row
            val = str(cell.value).strip().lower()
            if val.endswith('%'):
                num = float(val.strip('%'))
                if num < 80.0:
                    cell.fill = red_fill
                    cell.font = red_bold_font
        except (AttributeError, ValueError):
            pass

    # Merge bottom row columns (Estimated, Count, True) into one wide cell per date
    for i in range(len(dates)):
        start_col = 2 + (i * 3) # B is 2, E is 5, H is 8...
        end_col = start_col + 2
        ws.merge_cells(start_row=max_row, start_column=start_col, end_row=max_row, end_column=end_col)

    # Adjust column widths
    for col_idx in range(1, max_col + 1):
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = 14
    ws.column_dimensions['A'].width = 22 # Wider for Student Names

    # Freeze panes
    ws.freeze_panes = "B3"
    
    wb.save(xlsx_output)
    print(f"\nSuccess! Files saved in: {input_dir}")
    print(f" -> {os.path.basename(csv_output)}")
    print(f" -> {os.path.basename(xlsx_output)}")

if __name__ == "__main__":
    BASE_DIRECTORY = "ATTENDENCE RESULTS/Results"
    TARGET_FOLDER = "test 14"
    
    process_attendance(BASE_DIRECTORY, TARGET_FOLDER)